version: '3.7'

services:
  web:
    container_name: web
    volumes:
      - ./web:/project
    build: ./project
    ports:
      - "8000:8000"
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
